spring:
  application:
    name: login-auth-api

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

api:
  security:
    token:
      secret: ${JWT_SECRET:umaChaveQualquerParaDev}
